### ISSUE TITLE
SHM

### ISSUE THREAD

**Issue by feiqn** [edm64/round1-location-index#4]
We are opening a new store - SHM / South Hill Mall / Puyallup / WA, on Saturday July 16th :)

You also appear to be missing VCM / Vancouver Mall / Vancouver / WA

Finally, the hyperlink in your "about" is missing an "S" for /locations, /location is not a valid Round1 URL 

Thanks from the Round1 Team!

**Comment by edm64** [comment]
thanks for the info, and for catching the link I forgot about :v:
